# Generated by Django 4.1.1 on 2022-10-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
