# Generated by Django 4.1.1 on 2022-10-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0002_alter_post_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/headshot.jpg', upload_to='static/images'),
        ),
    ]
