# Generated by Django 4.1.1 on 2022-10-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('field', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('skills_1', models.CharField(max_length=200)),
                ('skills_2', models.CharField(max_length=200)),
                ('skills_3', models.CharField(max_length=200)),
                ('skills_4', models.CharField(max_length=200)),
                ('experience_1_title', models.CharField(max_length=200)),
                ('experience_1_dur', models.CharField(max_length=200)),
                ('experience_1_desc', models.CharField(max_length=200)),
                ('experience_2_title', models.CharField(max_length=200)),
                ('experience_2_dur', models.CharField(max_length=200)),
                ('experience_2_desc', models.CharField(max_length=200)),
                ('education_1', models.CharField(max_length=200)),
                ('education_1_dur', models.CharField(max_length=200)),
                ('education1_score', models.CharField(max_length=200)),
                ('education_2', models.CharField(max_length=200)),
                ('education_2_dur', models.CharField(max_length=200)),
                ('education2_score', models.CharField(max_length=200)),
            ],
        ),
    ]
